"""Shared Markdown helpers for the documentation generator."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path


HEADER = "<!-- AUTO-GENERATED by scripts/docgen — DO NOT EDIT BY HAND. Re-run `python -m scripts.docgen.generate` to refresh. -->\n"

PLACEHOLDER = "{{PLACEHOLDER}}"
UNKNOWN = "**Unknown — needs business input**"

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS = REPO_ROOT / "model-docs"

TODAY = date.today().isoformat()


def md_escape_pipe(s: str) -> str:
    """Escape pipes for Markdown table cells, replace newlines with <br>."""
    if s is None:
        return ""
    return (
        s.replace("|", "\\|")
        .replace("\r\n", "\n")
        .replace("\n", "<br>")
    )


def safe_filename(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", name).strip("_") or "Untitled"


def slugify(name: str) -> str:
    """Convert a heading to a GitHub-style anchor."""
    s = name.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    return s


_REVISION_LINE_RE = re.compile(r"^_Last generated: \d{4}-\d{2}-\d{2}_\s*$", re.MULTILINE)


def _normalise_for_compare(text: str) -> str:
    return _REVISION_LINE_RE.sub("", text)


def write(path: Path, content: str) -> bool:
    """Write ``content`` to ``path``. Returns True if the file was created or
    changed, False if existing content was byte-identical (after ignoring the
    daily ``_Last generated:`` revision line). Skipping unchanged writes
    preserves file mtimes so ``git status`` reflects real content changes only.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.endswith("\n"):
        content += "\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if _normalise_for_compare(existing) == _normalise_for_compare(content):
            return False
    path.write_text(content, encoding="utf-8")
    return True


def code_block(text: str, lang: str = "") -> str:
    text = (text or "").rstrip()
    if not text:
        return "_(empty)_"
    return f"```{lang}\n{text}\n```"


def audience_line(*audiences: str) -> str:
    return f"**Audience:** {', '.join(audiences)}"


def revision_line() -> str:
    return f"_Last generated: {TODAY}_"


def link(label: str, target: str) -> str:
    """Build a Markdown link with URL-encoded spaces."""
    return f"[{label}]({target.replace(' ', '%20')})"


def section_purpose(purpose: str, *audiences: str) -> str:
    return f"> **Purpose.** {purpose}\n>\n> {audience_line(*audiences)}\n>\n> {revision_line()}\n"


__all__ = [
    "HEADER",
    "PLACEHOLDER",
    "UNKNOWN",
    "REPO_ROOT",
    "DOCS",
    "TODAY",
    "md_escape_pipe",
    "safe_filename",
    "slugify",
    "write",
    "code_block",
    "audience_line",
    "revision_line",
    "link",
    "section_purpose",
]
